name: Build Android App (Flet 0.80.0)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 جلب الكود
        uses: actions/checkout@v4

      - name: 🐦 إعداد Flutter (الإصدار المطلوب 3.38.3)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.38.3' 

      - name: 🐍 إعداد بايثون
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 تثبيت Flet 0.80.0
        run: pip install flet==0.80.0

      - name: 🏗️ بناء تطبيق الأندرويد
        # إجبار البناء على التجاوز التلقائي
        run: flet build apk --yes
        env:
          FLET_FORCE_YES: "true"

      - name: 📤 حفظ ملف الـ APK
        uses: actions/upload-artifact@v4
        with:
          name: my-flet-app-apk
          path: build/apk/**/*.apk
